[general]
import = [
    "~/.config/alacritty/themes/themes/blood_moon.toml",
]

[window]
decorations = "None"
startup_mode = "Fullscreen"

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
size = 16

[keyboard]
bindings = [
    {key="$", mods="None", mode="Vi", action="Last"},
		# https://github.com/alacritty/alacritty/issues/4451#issuecomment-1982419177
    { key = "Tab", mods = "Control", chars = "\u001b[27;5;9~" },
    { key = "Tab", mods = "Control|Shift", chars = "\u001b[27;6;9~" },
]
