plugin {
  scroller {
    # Alignment
    center_active_column = 1
    center_active_window = 0
    # Sizes
    column_default_width = twothirds
    cyclesize_wrap = false
    column_widths = onehalf twothirds fivesixths one
    column_heights = threeeighths one
    # Navigation
    jump_labels_keys = euth
    jump_labels_scale = .2

    # Admit/Expel
    bind = $mainMod, E, scroller:admitwindow, l
    bind = $mainMod, U, scroller:admitwindow, r
    bind = $mainMod SHIFT, E, scroller:expelwindow, l
    bind = $mainMod SHIFT, U, scroller:expelwindow, r
    # Set Mode Modifiers submap
    # will switch to a submap called modifiers
    bind = $mainMod, backslash, submap, modifiers
    # will start a submap called "modifiers"
    submap = modifiers
    # Modes
    # TODO: Change the submap to setup the default height base on the mode -> 2/5 quand en colonne et 1 quand en ligne.
    bind = , C, scroller:setmode, col
    bind = , C, submap, reset
    bind = SHIFT, C, scroller:setmode, row
    bind = SHIFT, C, submap, reset
    # Position new window
    bind = , u, scroller:setheight, onehalf
    bind = , u, submap, reset
    bind = , h, scroller:setheight, one
    bind = , h, submap, reset
    bind = , right, scroller:setmodemodifier, after
    bind = , right, submap, reset
    bind = , left, scroller:setmodemodifier, before
    bind = , left, submap, reset
    bind = , prior, scroller:setmodemodifier, beginning
    bind = , prior, submap, reset
    bind = , next, scroller:setmodemodifier, end
    bind = , next, submap, reset
    # use reset to go back to the global submap
    bind = , escape, submap, reset
    # will reset the submap, meaning end the current one and return to the global one
    submap = reset
    # Sizes
    bind = $mainMod SHIFT, UP, scroller:fitsize, active
    bind = $mainMod SHIFT, RIGHT, scroller:cyclesize, +1
    bind = $mainMod SHIFT, LEFT, scroller:cyclesize, -1
    # Navigation
    bind = $mainMod, RETURN, scroller:jump
    bind = $mainMod SHIFT, RETURN, scroller:toggleoverview
  }
}

# # Admit/Expel
# bind = $mainMod, E, scroller:admitwindow, l
# bind = $mainMod, U, scroller:admitwindow, r
# bind = $mainMod SHIFT, E, scroller:expelwindow, l
# bind = $mainMod SHIFT, U, scroller:expelwindow, r
# # Set Mode Modifiers submap
# # will switch to a submap called modifiers
# bind = $mainMod, backslash, submap, modifiers
# # will start a submap called "modifiers"
# submap = modifiers
# # Modes
# # TODO: Change the submap to setup the default height base on the mode -> 2/5 quand en colonne et 1 quand en ligne.
# bind = , C, scroller:setmode, col
# bind = , C, submap, reset
# bind = SHIFT, C, scroller:setmode, row
# bind = SHIFT, C, submap, reset
# # Position new window
# bind = , u, scroller:setheight, onehalf
# bind = , u, submap, reset
# bind = , h, scroller:setheight, one
# bind = , h, submap, reset
# bind = , right, scroller:setmodemodifier, after
# bind = , right, submap, reset
# bind = , left, scroller:setmodemodifier, before
# bind = , left, submap, reset
# bind = , prior, scroller:setmodemodifier, beginning
# bind = , prior, submap, reset
# bind = , next, scroller:setmodemodifier, end
# bind = , next, submap, reset
# # use reset to go back to the global submap
# bind = , escape, submap, reset
# # will reset the submap, meaning end the current one and return to the global one
# submap = reset
# # Sizes
# bind = $mainMod SHIFT, UP, scroller:fitsize, active
# bind = $mainMod SHIFT, RIGHT, scroller:cyclesize, +1
# bind = $mainMod SHIFT, LEFT, scroller:cyclesize, -1
# # Navigation
# bind = $mainMod, RETURN, scroller:jump
# bind = $mainMod SHIFT, RETURN, scroller:toggleoverview
