# windowrulev2 = fullscreen, title:(^Logseq$)
# windowrulev2 = opacity 0.95, title:(^Logseq$)
windowrulev = bordersize 0, match:class (^showmethekey-gtk$)
windowrulev = suppress_event fullscreen, match:class .*
