# windowrulev2 = fullscreen, title:(^Logseq$)
# windowrulev2 = opacity 0.95, title:(^Logseq$)
windowrule = match:class (^showmethekey-gtk$), border_size 0 
windowrule = suppress_event fullscreen, match:class .*
# TODO firefox resize at 1, currently no corresponding windows rule for scrolling.
