set -gq allow-passthrough on
set -g visual-activity off

set-option -g prefix C-Space
unbind-key C-b          
bind-key C-Space send-prefix

set-environment -g TMUX_PLUGIN_MANAGER_PATH '/home/muffie/.local/share/tmux/plugins'

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_variant 'main' # 'main', 'moon' or 'dawn'

set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '/home/muffie/.local/share/tmux/plugins/tpm/tpm'
